version: '2.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    environment:
      ADMINER_DESIGN: dracula

  node-red:
    build:
      context: .
      dockerfile: ./node-red/Dockerfile
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"

  mosquitto:
    build:
      context: .
      dockerfile: ./mqtt/Dockerfile
    hostname: mqtt
    ports:
      - 1883:1883
      - 18883:8883
    # volumes:
    #   - ./mqtt/mosquitto-data:/mosquitto/data
    #   - ./mqtt/mosquitto-logs:/mosquitto/log
    #   - ./mqtt/mosquitto-conf:/mosquitto/config
    restart: unless-stopped

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword
      MYSQL_DATABASE: GenaralDB
      MYSQL_USER: NativasUser
      MYSQL_PASSWORD: welovepugs
    volumes:
      - ./mysql/mysql_tables:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana
    ports:
      - '13000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
